-libraryjars D:\WTK20\lib\mmapi.zip;D:\WTK20\lib\wma.zip;D:\WTK20\lib\midpapi.zip
-injars D:\WTK20\apps\Hotrotuyensinh\bin\Hotrotuyensinh.jar
-outjar C:\DOCUME~1\LENGOC~1\LOCALS~1\Temp\Hotrotuyensinh.jar
-keep public class * extends javax.microedition.midlet.MIDlet 
